### ISSUE TITLE
markovs() function throw exception

### ISSUE THREAD

**Issue by ilentt** [nomemory/mockneat#105]
When I follow the example at https://www.mockneat.com/docs/#markovs

The markovs() function it seem occurred error, despite I call get() or val() it's always throw exception error. I am not sure this error cause by my fault or something else. Would you please show me solution to solve it?

``
mock.markovs().size(512).type(MarkovChainType.LOREM_IPSUM).get();
``

![image](https://user-images.githubusercontent.com/11204504/136745719-bbc442e5-9a36-4d0c-85ea-09113c750cbb.png)

**Comment by nomemory** [comment]
@ilentt I've just tried with

```
        String loremIpsum = markovs().size(1024).type(LOREM_IPSUM).get();
        System.out.println(loremIpsum);
```

And it works for me.

What version are you using /?
