### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by jaytheking** [nomemory/mockneat#12]
I see you have extensive tests written but its hard to try and figure out how well the tests cover all of the code. Is it possible to get some code coverage stats on the readme?

Im potentially looking to use this in my tests and so far i havent really found another library that is fit for purpose and easy to use such as yours.

**Comment by nomemory** [comment]
I will generate some test coverage reports and  add them to the documentation. Thank you for looking at the library.

**Comment by nomemory** [comment]
@jaytheking I've added an interactive report on codecoverage that can be found at this link: https://codecov.io/gh/nomemory/mockneat . The report is dynamic and it's triggered through a Travis-CI build.

**Comment by jaytheking** [comment]
@nomemory ahhh cheers for that, appreciate you getting back to me about it quickly. Damn for a new library the coverage is great. 

Ive started with a test project and ill be seeing how it works, my main usage is for a DB mocking setup based on POJO.

Cheers again.

**Comment by nomemory** [comment]
@jaytheking Thank you, if you can, please keep my up-to-date with your progress when you are going to use the library. This will enable me making it more stable & better in the long run. 

Also feel free to contribute if you ever have time & mood.

Cheers!
