### ISSUE TITLE
Add possibility to directly mock data into database.

### ISSUE THREAD

**Issue by jaytheking** [nomemory/mockneat#15]
Just looking at the tutorial for mocking a MySQL database i had the thought that it would make things even better if you could directly store the resulting list into a database. A JPA provider could take care of generalising the sql code generation based on the the domain classes and the mockneat `list().val();` call can make a call to the JPA persist method for storing.

Im not familiar with the functional programming api in java 8 but if you can tell me what would be needed in order to integrate something like this into Mockneat i can help with that part.

**Comment by nomemory** [comment]
Actually you can do that by mocking (using reflect method) directly the JPA entities, and afterwards save them through. I am doing this already in a personal project. 

Or maybe I didn't understand correctly . You want to add a persistToDb() method in the MockUnit , just like val(), but instead of retrieving the value, actually persisting it ?

**Comment by jaytheking** [comment]
> Or maybe I didn't understand correctly . You want to add a persistToDb() method in the MockUnit , just like val(), but instead of retrieving the value, actually persisting it ?

yes this.

**Comment by nomemory** [comment]
I think this feature would prove to be quite complicated. Let me think a little bit and I will come with a reply.

**Comment by jaytheking** [comment]
I dont know a lot about the java functional API but i imagine for something like this there would need to be a wrapper around the JPA crud methods that can take in streams to store the results ?

**Comment by nomemory** [comment]
@jaytheking I've considered your suggestion but i think it will be difficult to implement.

Let's take for example this code:
``` java
MockNeat mock = MockNeat.threadLocal();
Map<String, List<Map<Set<Integer>, List<Integer>>>> result =
                mock.ints()
                    // List<Integer>
                    .list(2)
                    // Map<Set<Integer>, List<Integer>>
                    .mapKeys(2, mock.ints().set(3)::val)
                    // List<Map<Set<Integer>, List<Integer>>>
                    .list(LinkedList.class, 2)
                    // Map<String, List<Map<Set<Integer>, List<Integer>>>>
                    .mapKeys(4, mock.strings()::val)
                    .val();
```
At the end it will random fill a complex structure like `Map<String, List<Map<Set<Integer>, List<Integer>>>>`. If we add a `persistToDb()` method just like `val()` is at the `MockUnit` interface level what we are going to persist in this case ?

The objects can be easily persisted (each developer can actually write it's own persisting mechanism) by using the method called `consume()` that is defined at the `MockUnit` interface level.

For example:
```java
  m.reflect(EmployeePC.class)
                                .field("uuid",
                                     m.uuids())
                                .field("username",
                                     m.users())
                                .field("operatingSystem",
                                     m.from(new String[]{"Linux", "Windows 10", "Windows 8"}))
                                .field("ipAddress",
                                        m.ipv4s().type(CLASS_B))
                                .field("macAddress",
                                        m.macs())
                                .list(2))
                                .consume(list -> /** THE CODE THAT PERSISTS THE DATA IN THE DB HERE */);
```

In this way the developer has the freedom to consume & persist the data using JDBC directly or ORM || JPA libraries. 

So my feeling is that the library should be "neutral" in this sense.
