### ISSUE TITLE
Add the possibility to generate a random phone number

### ISSUE THREAD

**Issue by sayadi** [nomemory/mockneat#16]
This is very common

**Comment by nomemory** [comment]
@muhammed-sayadi Do you have any suggestions on how this can be implemented ? 

For the moment for phone numbers you can actually use [mockNeat.fmt()](https://github.com/nomemory/mockneat/wiki/MockNeat#fmt) or [mockNeat.regex()](https://github.com/nomemory/mockneat/wiki/MockNeat#regex).

**Comment by muhammed-sayadi** [comment]
@nomemory 
Thanks. mockeNeat.fmt would indeed do for now.

Thinking about it, the format would be one of the ITU standards; E.123 and E.164 [from the link below].

A quick Google search returned this:
[Helpful Stackoverflow question ](https://stackoverflow.com/questions/15745545/is-there-a-standard-for-phone-numbers)

Country codes can be stored as well.

[A list of country codes](https://www.verizon.com/support/residential/phone/homephone/general+support/long+distance+calling/general/95208.htm)

Then something like:
mockNeat.phoneNumbers() // returns a random phone number in the default standard or
mockNeat.phoneNumbers().type(E164) // returns a random phone number in the specified standard or even 
mockNeat.phoneNumbers().countries().us() // returns a random US phone number in the default standard

**Comment by nomemory** [comment]
@muhammed-sayadi thank you for giving me the details.

Are you interested in picking this up (if you have time for contributions). If not I can pick this up, whenever I free myself some time.

**Comment by muhammed-sayadi** [comment]
@nomemory My pleasure. This is helpful and can easily find good use cases for in the future for many.

I will when I have some time as well (would need at least after 19th Dec)

**Comment by nomemory** [comment]
Ok. Thanks for your implication Muhammed. It is indeed a good feature. I didn't know the phone numbers where standardized. 

Another good idea to include in the future would be street addresses and postal codes. 

Thanks for the suggestion.
