### ISSUE TITLE
Add the possibility to register Custom MockUnits to the MockNeat object.

### ISSUE THREAD

**Issue by nomemory** [nomemory/mockneat#2]
Write a generic mechanism that allows the user to register Custom MockUnits with a MockNeat instance and/or globally.

`mock.register("name", Class, MockUnit)`
`mock.custom("name").val`

To investigate what is the best strategy to achieve this.

**Comment by nomemory** [comment]
For the moment it will not be implemented.

**Comment by bwollny** [comment]
Hi. Would be nice to have such a feature. We are using it for German customers and need extensions for German dicts...

**Comment by nomemory** [comment]
www.mockneat.com/docs/#files

^ this might be useful to use if you have data in files and you want to generate arbitrary values from there.

Registering custom mockunits can be tricky because of how the type system works in Java. 

If you describe in greater detail your exact scenario I can help you with an workaround. 

Meanwhile I will think of a solution to register mockunits, but it will be probably quite hackish.

Ps: check www.mockneat.com a lot of the things have changed in the last version. Don't forget to look at the tutorial.

**Comment by bwollny** [comment]
Hi Andrei,

quick reply, thanks. What we consider to do is to have different dicttypes than yours. Unfortunately, it is not possible to extend mockneat in that way. And yes, you are right we want to have our data in files. 

To give you all of our information it will take a while. :)

What do you think about having a key value mockunit? Or a pair mock unit?

**Comment by nomemory** [comment]
Hey, I am currently in travel mode. Let me think and I will come with an answer next week.

Meanwhile you can use the files().from(...) method to get arbitrary information from files.

**Comment by nomemory** [comment]
@bwollny 

DictTypes are enums, and they usually represent an internal txt file that is included in the JAR.

If you want to read data from "external" sources, like files from the disk you can use the method I've mentioned: 

[www.mockneat.com/docs/#files](www.mockneat.com/docs/#files)

For example, let's say I have a file called `german-words` in my path. I can read information from it using something like this:

```java
package net.andreinc.mockneat.examples;

import net.andreinc.mockneat.abstraction.MockUnitString;
import static net.andreinc.mockneat.types.enums.StringFormatType.UPPER_CASE;
import static net.andreinc.mockneat.unit.objects.Probabilities.probabilities;
import static net.andreinc.mockneat.unit.text.FromFiles.files;
import static net.andreinc.mockneat.unit.text.Words.words;

public class FromFilesExample {

    // Returns an arbitrary word from the "external" file
    public static MockUnitString germanWords() {
        return files().from("german-words");
    }

    public static void main(String[] args) {

        probabilities(String.class)
                    .add(0.3, germanWords().format(UPPER_CASE)) // Here we use for example the custom unit - 30% chances of generating an UPPER CASE German word from the external file
                    .add(0.3, words().nouns()) // 30% chances of generating an English noun
                    .add(0.4, words().adjectives()) // 40% chances of generating an English adjective
                .mapToString()
                .accumulate(20, ", ") // concatenate using "," as the seperator
                .consume(System.out::println);
    }
}
```

PS: Don't forget to get the latest version of MockNeat 0.3.+

**Comment by bwollny** [comment]
Hey Andrei,

i just tried it a few minutes ago, but i get the following error: 

``Exception in thread "main" java.lang.NoClassDefFoundError: net/andreinc/aleph/AlephFormatter
	at net.andreinc.mockneat.utils.ValidationUtils.notEmpty(ValidationUtils.java:113)
	at net.andreinc.mockneat.unit.text.FromFiles.from(FromFiles.java:51)
	at com.commerzbank.raki.business.ccs.mock.Titles.supplier(Titles.java:20)
	at net.andreinc.mockneat.abstraction.MockUnit.val(MockUnit.java:70)``

where titles ist a new MockUnit with the following method:

```
Override
	public Supplier<String> supplier() {
		return mockNeat.files().from("C:........\\resources\\dict\\titles").supplier();

	}
```
I am using version 0.3.4.

Do you know what iam doing wrong?

Regards Bernd

**Comment by nomemory** [comment]
Can you give me the full code ? I cannot understand what's wrong from what you are showing.

**Comment by bwollny** [comment]
Ouhhh, there is a dependency to your project that hosts the AlephFormatter....thats the reason. our maven didnt fetch the dependency...

**Comment by nomemory** [comment]
Is it working now ? Or still it has problem with the dependency ?

**Comment by bwollny** [comment]
I do not have the possibility to add the dependency right now. i am working in an environment where there are some restrictions to add new software....so unfortunately right now i cannot test the file()-method...

Thought about your mock.register(...) idea? would be nice to have something like that.

How would you implement something like a <key, value> mockunit? i'm currently having this issue.
