### ISSUE TITLE
Add support to convert JSON Schema draft to sample JSON data

### ISSUE THREAD

**Issue by manas019** [nomemory/mockneat#21]
Add support to convert JSON Schema lets say in draft 6 to generate random data.
User will provide  JSON Schema in draft  and the library should return random data.
This would help in mocking test data from swagger directly.

**Comment by gsaisn** [comment]
Good to support either JSON Schema or a template (like in json-generator). Could not find any java lib to do this.

**Comment by nomemory** [comment]
@gsain

There is something I was thinking for a long time but recently I have not enough time to allocate to this. 

Currently there is an example on the wiki on how you can generate jsons as long as you have the data model classes, but I know it can be cumbersome as more work is needed for the developer.

There is another issue open about generating data based on openapi / swagger specs. 

I will leave those open for the time being and at the end of summer I might pick those up.
