### ISSUE TITLE
Issue importing lib in a gradle build

### ISSUE THREAD

**Issue by gsaisn** [nomemory/mockneat#22]
Gradle build fails with error:
org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find net.andreinc.mockneat:mockneat:0.1.7.

Similar error for previous versions too.

**Comment by nomemory** [comment]
Hello,

I believe you didn't include the jcenter() as the repo in your build file:

I've just created a test project and in my `build.gradle` file I have the following configuration:

```
repositories {
    jcenter()
    mavenCentral()
}

dependencies {
    compile 'net.andreinc.mockneat:mockneat:0.1.7'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
```

For me it works.

cc: @gsaisn

**Comment by gsaisn** [comment]
Thanks. Works fine when I created a fresh project too. 
Faced the issue only when I added the dependency into a multi module project. I already have jcenter() as a repo in the project.
A --stacktrace returns just the error pasted in my original comment. And this error appears only for the mockneat dependency. Wondering what to check next!

**Comment by gsaisn** [comment]
Fixed it. Confusion between buildscript repository and project repository that missed the eye. :(

**Comment by nomemory** [comment]
@gsaisn 

No problem, i am happy it's fixed.
