### ISSUE TITLE
Middle Name support to mockneat

### ISSUE THREAD

**Issue by rajib76** [nomemory/mockneat#24]
Hi, I felt the need of this feature in one of my engagement and went ahead and developed that feature. I have also created a pull request to include it in main branch. This is the first time I am contributing a piece of code in an open source project. So, I am not sure if I did it correctly. Please let me know if I have made any mistakes/violated any rules while creating the PR

**Comment by nomemory** [comment]
@rajib76 

Thanks for contributing. For the moment I don't see any PR  open. Once you open that I can review it. 

Andrei

**Comment by rajib76** [comment]
Please check now, for some reason I have to create the pull request again

**Comment by rajib76** [comment]
It looks like the code coverage failed but it shows IPV6 file which I have not touched at all:(

**Comment by rajib76** [comment]
Closing per discussion Andrei
