### ISSUE TITLE
Change int to long for number of records passed to list...

### ISSUE THREAD

**Issue by rajib76** [nomemory/mockneat#29]
I will work on it and send a PR shortly. Currently the code takes only int for number of records. If we need billions of records created, we will need to change it to long

default MockUnit<List<T>> list(Supplier<List<T>> listSupplier, int size)

I am planning to add another method which will take long as an input.

**Comment by rajib76** [comment]
It will work till 2,147,483,647. For more than this we will need long.

**Comment by nomemory** [comment]
I don't think someone needs to keep in memory a list bigger than Integer max.

**Comment by rajib76** [comment]
Hmm, I agree with you but should we look at any other option on how we can make it work if the need is to create large data let's say 3 billion records. May be some option to create the data in splits and write it in disk.

**Comment by nomemory** [comment]
It's highly improbable someone would want to create a 3 billion records data set.

Still if you want to write data in chunks you can do it in a series of way:

For example:
```java
 MockNeat m = MockNeat.threadLocal();

        int numStep = 10;
        int listSize = 1000;

        m.csvs()
         .column(m.intSeq())
         .column(m.names())
         .column(m.cities().capitals())
         .column(m.days())
         .column(m.creditCards().amex())
         .list(() -> new ArrayList<>(), listSize)
         .consume(numStep,  (step, list) -> {
             try { Files.write(Paths.get("test.csv"), list, CREATE, WRITE, APPEND); }
             catch (IOException e) { e.printStackTrace(); }
         });
```
