### ISSUE TITLE
Allow option to provide BIN prefix when generating credit card number

### ISSUE THREAD

**Issue by lazycodeninja** [nomemory/mockneat#30]
Congratulations on a cool library, "neat" is an appropriate name. 👍 

I was planning to use the `creditCards()` method to easily generate a credit card number, but need it to be generated with a specific BIN else it will be rejected as invalid in the system I'm testing.  From the code the card prefix is taken from the `CreditCardType` enum, which in the case of Visa is just the first digit (4).  From what I've read this is the IIN, the issuer identification number.

It would be nice if `CreditCards` had another method to specify a pool of BINs to use when generating the number, e.g.

```
String cardNumber1 = mockNeat.creditCards().visa().bins(445434).val();
String cardNumber2 = mockNeat.creditCards().visa().bins(445434, 414433).val();
```

**Comment by lazycodeninja** [comment]
I thought I'd try to code this up and submitting a pull request, but it's a little trickier than I thought.  At first glance I thought it was a simple builder pattern and I'd just need another method in `CreditCards` to set the BIN, but after looking at the code I see that this isn't the case; it's not possible to chain methods from anything other than `MockUnitString`.  I thought it may be possible instead to just bypass the type when specifying the bin, e.g.
```
String cardNumber1 = mockNeat.creditCards().bin(445434).val();
```
since we no longer need the prefix provided by `CreditCardType`, but then the length is unknown.

**Comment by nomemory** [comment]
@lazycodeninja 

Thanks for the interest. In the latest version, added today, check the custom() method on creditCards(). 

Example: 

```java
 M.creditCards()
         .custom(15, 445434, 414433)
         .consume(100, (i, cc) -> System.out.println(cc));

**Comment by lazycodeninja** [comment]
Thanks you very much, that was very quick.

Yes the new method does just what I need. 👍

**Comment by nomemory** [comment]
@lazycodeninja, 

Glad it helped.
