### ISSUE TITLE
Web API data sources

### ISSUE THREAD

**Issue by invalid-packet** [nomemory/mockneat#32]
There exist services like https://randomuser.me/ which provide restful api to get random data in json format, thus not requiring a local database. Would it be too far from this project idea to incorporate a generic  rest api in order to get data from the web? Something like:

```
MockNeat.threadLocal()
         .fromRest("/someurl")
         .params(...)
         .deserializer(SomeDeserializer.class)
         .val()
```

**Comment by nomemory** [comment]
@invalid-packet this sounds like an idea. 
In the next two weeks I am on holidays, but when I comeback i will give it a thought.

**Comment by nomemory** [comment]
@invalid-packet 

I gave this feature a though and I don't think it's a good idea to implement this in MockNeat. The library should stay "agnostic" when it comes to REST calls or having a deserializer/serializer.

But you can create your own custom MockUnit if you want.

If you need help on how you can create that, give me a shout and I can help further.

Andrei
