### ISSUE TITLE
mockneat unable to mock final static members of target mock object

### ISSUE THREAD

**Issue by mnreddy7** [nomemory/mockneat#33]
Java beans in my projects are serializable and all have serialVersonUID which are final. When I try to mock that object, It gives me **IllegalArgumentException: Field is marked as final. It can't be modified. Please remove it from field list**. I checked if there is any option to ignore final members while creating mockneat object. But I couldn't find one.

**Comment by mnreddy7** [comment]
@nomemory Can you please have a look at this issue?

**Comment by nomemory** [comment]
Hello,

I will take a look when I comeback from the holidays.

Meanwhile take a look at the filler() method instead of reflect() that should be the preferred method to create objects.

ANDREI

PS: can you please also add an example to see exactly what is not working .

**Comment by nomemory** [comment]
Closing as no more info supplied.
