### ISSUE TITLE
provide more kotlin (and scala?) friendly supplier.val() 

### ISSUE THREAD

**Issue by jasperblues** [nomemory/mockneat#34]
```
val email = mock.emails().`val`()
```
^-- its not bad, but maybe an alias?

**Comment by nomemory** [comment]
Yes. That was something I was thinking about.

Any method name suggestions ?

**Comment by jasperblues** [comment]
How about `supply()`, `build()` or `get()` ?

**Comment by nomemory** [comment]
@jasperblues 

In the latest version 0.2.6 this method was introduced:
https://github.com/nomemory/mockneat/wiki/MockUnit#get

Hope it helps.

**Comment by jasperblues** [comment]
DO you still publish to Maven Central?
