### ISSUE TITLE
Ability to generate Times?

### ISSUE THREAD

**Issue by StephenOTT** [nomemory/mockneat#42]
Seems you can generate Dates, but is is possible to generic Dates with Times ?

**Comment by nomemory** [comment]
Something like the (not so) new [`LocalDateTime`](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html) ?

No, it's only possible to generate `LocalDate` (for the moment).

In the future it will be possible, it's one of the features I wanted to add for some time, but never had the *time* :).

**Comment by StephenOTT** [comment]
k great.  Just wanted to make sure was not missing anything!

**Comment by nomemory** [comment]
@StephenOTT This is going to be implemented in the next version! Stay tuned.

**Comment by StephenOTT** [comment]
Great. Thanks !!

**Comment by KolyaMetallist** [comment]
As a workaround I use the following:
`Timestamp.valueOf(mock.localDates().val()
                                        .atTime(mock.ints().rangeClosed(0, 23).val(),
                                            mock.ints().rangeClosed(0, 59).val(),
                                            mock.ints().rangeClosed(0, 59).val()))`
