### ISSUE TITLE
Generate Numbers with a lower bound?

### ISSUE THREAD

**Issue by StephenOTT** [nomemory/mockneat#43]
it seems to be possible to generate a Upper bound using the `.bound()` method when working with Numbers.  But is it possible to set a lower bound?  The use case is mainly to enforce positive numbers

1. `>= 0`
1. `> 0`

**Comment by nomemory** [comment]
Hey @StephenOTT,

Thanks for trying the library.

Is this helpful: https://www.mockneat.com/docs#ints

```java
Integer ranged = ints().range(10, 20).get();
// Possible Output: 19
```

**Comment by nomemory** [comment]
PS: To have an idea of all the features of the library, don't forget to check the tutorial: https://www.mockneat.com/tutorial/

**Comment by StephenOTT** [comment]
@nomemory Thanks for the quick response.  So yes Range is what i used as the workaround, but it requires a upper bound.  This is quite burdensome when you want to only set a min of 0 or 1 and you are using a Long for example.

**Comment by nomemory** [comment]
@StephenOTT This will be implemented in the next version. Thanks for the idea.

**Comment by StephenOTT** [comment]
Great. Thanks 🤘🏻

**Comment by nomemory** [comment]
@StephenOTT 

Didn't forget about the request.
So now you can use lowerBound(), like in the following example:


```
        ints().lowerBound(100000)
              .mapToString()
              .accumulate(10, ",")
              .consume(System.out::println);
```

PS: Don't forget to update to 0.3.6

**Comment by StephenOTT** [comment]
@nomemory Thanks for the great support.  I will check it out!
