### ISSUE TITLE
Requirement to create data for a retail industry...

### ISSUE THREAD

**Issue by rajib76** [nomemory/mockneat#54]
Hi, I have a need to create a dataset for a retail industry where we need to create a list of edible and non-edible products. The use case is that based on the products bought by customers, they get rewards. This use case will also help to cross sell and up sell. I am thinking whether we should add a feature to create domain specific dataset. In this case it will produce a list of edible(like milk, meat) and non-edible(bath tissue etc). 

Thanks

**Comment by nomemory** [comment]
If you have this type of data as text, it can very easy to integrate in the library as a dictionary.
