### ISSUE TITLE
Unable to use PostgreSQL escaper with SQLInserts

### ISSUE THREAD

**Issue by luciano-fiandesio** [nomemory/mockneat#60]
The method `public SQLInserts column(String column, MockUnit mockUnit, UnaryOperator<String> sqlFormatter) ` in class `net.andreinc.mockneat.unit.text.SQLInserts` does not work with the Postgres and MySQL escapers, since both escaper return a `Function` and not a `UnaryOperator`.

This is in contrast with the documentation here: https://www.mockneat.com/tutorial#sql-inserts

As a temporary fix, I have created a local copy of PostgreSQL that uses  UnaryOperator.

**Comment by nomemory** [comment]
@luciano-fiandesio Thank you for reporting the bug. When I have some spare time I will be able to look into it.

**Comment by nomemory** [comment]
Hello, in version 0.3.7 UnaryOperator the problem should not appear.
If it persists please announce me.
