### ISSUE TITLE
localDates() does not work when using a formatter that contains time 

### ISSUE THREAD

**Issue by luciano-fiandesio** [nomemory/mockneat#61]
This code:
`localDates().thisYear().display(ISO_LOCAL_DATE_TIME)`

fails, because `ISO_LOCAL_DATE_TIME` uses `HOUR_OF_DAY`, `MINUTE_OF_HOUR`, `SECOND_OF_MINUTE` but the formatted class is `LocalDate` which has no reference to time.

**Comment by nomemory** [comment]
@luciano-fiandesio Thank you for reporting the bug. When I have some spare time I will be able to look into it.

**Comment by luciano-fiandesio** [comment]
I'm happy to provide a patch, just unsure how to handle it. 
1) remove completely the DATE TIME enum 
2) throw an exception if a DATE TIME is used with localDates()

any other idea?

**Comment by nomemory** [comment]
I believe the solution would be to deprecate the method. 
Throw an exception in the deprecated method.
Create a new ENUM to support the some pre-defined formats.

**Comment by nomemory** [comment]
@luciano-fiandesio I've deprecated the methods for the moment.
