### ISSUE TITLE
Industries is misspelled

### ISSUE THREAD

**Issue by osi** [nomemory/mockneat#68]
https://github.com/nomemory/mockneat/blob/60e53c03a55a1af58e41685587e922b50c707b23/src/main/java/net/andreinc/mockneat/MockNeat.java#L410

should be `industries`

**Comment by nomemory** [comment]
You are indeed right. I will fix this with the next release. Thank you for noticing.

**Comment by osi** [comment]
no worries, thanks for the library!

**Comment by nomemory** [comment]
Fixed in the latest version 
```compile 'net.andreinc.mockneat:mockneat:0.3.8'```
