### ISSUE TITLE
using list(MockUnitInt) doesn't generate a new random value each time.

### ISSUE THREAD

**Issue by osi** [nomemory/mockneat#72]
I am trying to generate lists of data with random size. I started with

```
MockUnit<T> things;
MockUnit<List<T>> listsOfThings = things.list(ints().range(0, 10));
```

my expectation from looking at the API was that each time I called `listOfThings.val()` I'd get a new list with a random size. in practice, the random size is evaluated once, and I get lists of the same size each time.

i've worked around this by doing

```
MockUnit<List<T>> listsOfThings = ints().range(0, 10).map( size -> things.list(size).val());
```

but that feels awkward.

what's the intention of `MockUnit.list(MockUnitInt)` ? would you be open to a PR that evaluates the random size each time a new `val` is requested?

**Comment by nomemory** [comment]
Hey, thanks for stopping by. It's true, things don't work as expected. Let me take a look to understand what I've missed.

**Comment by nomemory** [comment]
@osi 

Tried a quick fix.

Can you please try your scenario with the latest version:

```
compile 'net.andreinc.mockneat:mockneat:0.3.8'
```

**Comment by nomemory** [comment]
@osi I am also more than open to any PR. 

If you have additional ideas don't hesitate to share them.

**Comment by osi** [comment]
thanks for the fix! what you did fixes my scenario (here's a snippet that exercises it)

```
        MockNeat mn = MockNeat.threadLocal();

        MockUnit<List<String>> strings = mn.strings()
                                           .size(5)
                                           .list(mn.ints().rangeClosed(1, 2));

        for (int i = 0; i < 10; i++) {
            System.out.println(strings.val().size());
        }
```

good to know about future PRs. (I like to discuss changes to projects with people first, rather than dropping off a PR with no context)

**Comment by nomemory** [comment]
Thank you for your interest. I enjoy when people actually raise those kinds of issues. 

Regarding the PRs, there are many ideas hanging, but one of the things I was interested in building were:

- implementing mockneat in other languages, e.g.: JavaScript . The fakers in the js world aren't very smart;
- building a mockneat server that can be used to mock rest APIs easier (descriptive approach)
- adding mockneat @Annotations so you can decorate the model classes with hints about the data the fields are holding
- improve the https://www.mockneat.com/docs/#reflect method so objects can be automatically populated in a recursive manner.
- etc.

**Comment by osi** [comment]
Good to hear your ideas! I've been primarily using the project to populate tables in a relational DB. I borrowed some from the existing `SQLInsert` but had made my own abstraction a bit more tailored to how I'm using it.  I'll keep your goals in mind as I continue to use the library and help enhance it appropriately.
