### ISSUE TITLE
Website search broken

### ISSUE THREAD

**Issue by Jazzepi** [nomemory/mockneat#74]
Searching for anything in the website produces hits that look correct but the links presented do not work. They all look like this.

https://www.mockneat.com/undefined

**Comment by nomemory** [comment]
@Jazzepi Thanks for stopping by. I will be able to fix the two issues you've mentioned in the following weeks.

Meanwhile, if you see anything else you would like to improve/remove/delete/add from the documentation:

https://github.com/nomemory/mockneat-site

(Every commit on git will trigger a new build in the production site, so changes are instant).
