### ISSUE TITLE
Markovs doesn't honor RandomType

### ISSUE THREAD

**Issue by bin01** [nomemory/mockneat#77]
I have a use case to have repeatable text generation based on a given seed. It appears that Markovs doesn't honor RandomType.OLD as it directly relies on ThreadLocalRandom. Please let me know if you would like me to create a pull request to fix it.

**Comment by nomemory** [comment]
@bin01 Any PR is much appreciated. Thank you!

**Comment by bin01** [comment]
@nomemory Could you please look into the PR when you get a chance?

**Comment by nomemory** [comment]
@bin01 Thank you for the PR. I was a little bit busy at the moment. But I will review it as soon I have some time. Maybe till the end of the week ? Is that ok ?

Also, as far as I remember I've moved the markov part in the markovneat library and mockneat uses markovneat for markov related things.

**Comment by nomemory** [comment]
I think the PR was made on an older version of the library.

Most of the Markov related classes have been moved here:
https://github.com/nomemory/markovneat

I think that's the place where we should do the changes.

**Comment by bin01** [comment]
Oops, I will decline that PR and create it against the correct repo.
