### ISSUE TITLE
Antivirus complains of Java Trojan for mockneat-0.3.8.jar

### ISSUE THREAD

**Issue by dishantkamble** [nomemory/mockneat#92]
My antivirus complains of the following message for the **mockneat** library. The version I am using is **0.3.8**.

**`Virus: Java.Trojan.GenericGBA.20288`**

Is there any possible changes that can be made in the next version of this library so as to avoid such for future versions?

**Comment by nomemory** [comment]
@dishantkamble 

The current version is `0.4.1`, but without giving me more details, I don't know what to say about that "virus" ? What classes are problematic ?

This is the first time I am hearing this. Where are you downloading it from ?

Andrei

**Comment by dishantkamble** [comment]
I have added it to my pom. It takes it from maven.

The antivirus scanner does not give any more details than this unfortunately.

**Comment by nomemory** [comment]
What is the antivirus ? Maybe I can contact them.

**Comment by dishantkamble** [comment]
Microsoft Defender ATP

**Comment by nomemory** [comment]
I will contact Microsoft to understand better what's happening. Thanks for notifying me about this.

**Comment by nomemory** [comment]
@dishantkamble I've sent the request to Microsoft for this false positive. 

If you want to help you can also submit the .jar file as a false positive:

https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/antivirus-false-positives-negatives

**Comment by nomemory** [comment]
I've contacted the security team. It's a false positive. Should be fixed in the future.
