### ISSUE TITLE
probabilities use double loss of accuracy

### ISSUE THREAD

**Issue by EricZhangxd** [nomemory/mockneat#93]
MockNeat m = MockNeat.threadLocal();
    System.out.println(m.probabilites(Integer.class)
        .add(0.1, m.ints().range(0, 1))
        .add(0.1, m.ints().range(1, 2))
        .add(0.2, m.ints().range(2, 3))
        .add(0.2, m.ints().range(3, 4))
        .add(0.3, m.ints().range(4, 5))
        .add(0.1, m.ints().range(5, 6))
        .val());

throw error java.lang.IllegalArgumentException: Probabilities sum cannot be bigger (>) than '1.0'. but actually sum is 1.0
it happened when add 0.3, lastVal is 0.6000000000000001

**Comment by nomemory** [comment]
@EricZhangxd I am working on a fix. Realistically speaking it will be ready by end of next week.
Thank you for taking your time to report this issue.

**Comment by nomemory** [comment]
@EricZhangxd the bug should be fixed in the latest version `0.4.2`. Can you please see if the issue is still persisting ?

**Comment by EricZhangxd** [comment]
@nomemory it works, thanks !
