### ISSUE TITLE
Question: Would be viable to use reflection to call mockneat data generators ?

### ISSUE THREAD

**Issue by cvgaviao** [nomemory/mockneat#94]
I'm using my own tool in order to create pojos and test cases based on a set of json schemas. 
Now I'm investigating the mockneat tool in order to populate those tests.
 
Since I already have the json schema and I could tag each pojo's attribute with any value. For example, I could have one tagged with "x-gen-names.FIRST_NAME". 

Do you think that would be possible to instantiate a generator (names in the example below) and call its get method using reflection?

**Comment by nomemory** [comment]
Hi, 

I think it's possible. Every generator is a MockUnit (that's the interface). And also a specific class that implements this interface or a more specific one (MockUnitString, MockUnitInt, etc.). 

For example Names: https://github.com/nomemory/mockneat/blob/master/src/main/java/net/andreinc/mockneat/unit/user/Names.java

I don't see any reason it won't work what you want to achieve. You can keep an instance of Names in `xgen.First_Name` and then call get() through reflection to get a different name all the time.

Depending on how much you can modify your internal tool, you can also mingle scripts in the JSON you are using for your schemas. I did something similar in: 
https://github.com/nomemory/serverneat#json-response-dynamic---using-mockneat

**Comment by nomemory** [comment]
@cvgaviao Any luck? Need any help?
